apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: g0r3hgg9h-nodejs
  janus-idp.io/tekton: g0r3hgg9h-nodejs
  backstage.io/kubernetes-id: g0r3hgg9h-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g0r3hgg9h-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
