apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: g0r3hgg9h-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: g0r3hgg9h-nodejs 
  name: g0r3hgg9h-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: g0r3hgg9h-nodejs 
